In [35]:
# Importing relevant libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.metrics import r2_score


In [36]:
data = pd.read_csv("Tetuan City power consumption.csv")

In [37]:
data

DateTime  Temperature  Humidity  Wind Speed  \
0         1/1/2017 0:00        6.559      73.8       0.083   
1         1/1/2017 0:10        6.414      74.5       0.083   
2         1/1/2017 0:20        6.313      74.5       0.080   
3         1/1/2017 0:30        6.121      75.0       0.083   
4         1/1/2017 0:40        5.921      75.7       0.081   
...                 ...          ...       ...         ...   
52411  12/30/2017 23:10        7.010      72.4       0.080   
52412  12/30/2017 23:20        6.947      72.6       0.082   
52413  12/30/2017 23:30        6.900      72.8       0.086   
52414  12/30/2017 23:40        6.758      73.0       0.080   
52415  12/30/2017 23:50        6.580      74.1       0.081   

       general diffuse flows  diffuse flows  Zone 1 Power Consumption  \
0                      0.051          0.119               34055.69620   
1                      0.070          0.085               29814.68354   
2                      0.062          0.100               29128.10127   
3                      0.091          0.096               28228.86076   
4                      0.048          0.085               27335.69620   
...                      ...            ...                       ...   
52411                  0.040          0.096               31160.45627   
52412                  0.051          0.093               30430.41825   
52413                  0.084          0.074               29590.87452   
52414                  0.066          0.089               28958.17490   
52415                  0.062          0.111               28349.80989   

       Zone 2  Power Consumption  Zone 3  Power Consumption  
0                    16128.87538                20240.96386  
1                    19375.07599                20131.08434  
2                    19006.68693                19668.43373  
3                    18361.09422                18899.27711  
4                    17872.34043                18442.40964  
...                          ...                        ...  
52411                26857.31820                14780.31212  
52412                26124.57809                14428.81152  
52413                25277.69254                13806.48259  
52414                24692.23688                13512.60504  
52415                24055.23167                13345.49820  

[52416 rows x 9 columns]

In [38]:
data['DateTime'] = pd.to_datetime(data['DateTime'])

In [39]:
data['hour'] = data['DateTime'].dt.hour
data['day_of_week'] = data['DateTime'].dt.dayofweek
data['month'] = data['DateTime'].dt.month


In [40]:
data

DateTime  Temperature  Humidity  Wind Speed  \
0     2017-01-01 00:00:00        6.559      73.8       0.083   
1     2017-01-01 00:10:00        6.414      74.5       0.083   
2     2017-01-01 00:20:00        6.313      74.5       0.080   
3     2017-01-01 00:30:00        6.121      75.0       0.083   
4     2017-01-01 00:40:00        5.921      75.7       0.081   
...                   ...          ...       ...         ...   
52411 2017-12-30 23:10:00        7.010      72.4       0.080   
52412 2017-12-30 23:20:00        6.947      72.6       0.082   
52413 2017-12-30 23:30:00        6.900      72.8       0.086   
52414 2017-12-30 23:40:00        6.758      73.0       0.080   
52415 2017-12-30 23:50:00        6.580      74.1       0.081   

       general diffuse flows  diffuse flows  Zone 1 Power Consumption  \
0                      0.051          0.119               34055.69620   
1                      0.070          0.085               29814.68354   
2                      0.062          0.100               29128.10127   
3                      0.091          0.096               28228.86076   
4                      0.048          0.085               27335.69620   
...                      ...            ...                       ...   
52411                  0.040          0.096               31160.45627   
52412                  0.051          0.093               30430.41825   
52413                  0.084          0.074               29590.87452   
52414                  0.066          0.089               28958.17490   
52415                  0.062          0.111               28349.80989   

       Zone 2  Power Consumption  Zone 3  Power Consumption  hour  \
0                    16128.87538                20240.96386     0   
1                    19375.07599                20131.08434     0   
2                    19006.68693                19668.43373     0   
3                    18361.09422                18899.27711     0   
4                    17872.34043                18442.40964     0   
...                          ...                        ...   ...   
52411                26857.31820                14780.31212    23   
52412                26124.57809                14428.81152    23   
52413                25277.69254                13806.48259    23   
52414                24692.23688                13512.60504    23   
52415                24055.23167                13345.49820    23   

       day_of_week  month  
0                6      1  
1                6      1  
2                6      1  
3                6      1  
4                6      1  
...            ...    ...  
52411            5     12  
52412            5     12  
52413            5     12  
52414            5     12  
52415            5     12  

[52416 rows x 12 columns]

In [41]:
data = data.drop('DateTime', axis=1)


In [45]:
data.isna().sum()

Temperature                  0
Humidity                     0
Wind Speed                   0
general diffuse flows        0
diffuse flows                0
Zone 1 Power Consumption     0
Zone 2  Power Consumption    0
Zone 3  Power Consumption    0
hour                         0
day_of_week                  0
month                        0
dtype: int64

In [46]:
X = data[['Temperature','Humidity','Wind Speed','general diffuse flows','diffuse flows','hour','day_of_week','month']]

In [47]:
X

Temperature  Humidity  Wind Speed  general diffuse flows  \
0            6.559      73.8       0.083                  0.051   
1            6.414      74.5       0.083                  0.070   
2            6.313      74.5       0.080                  0.062   
3            6.121      75.0       0.083                  0.091   
4            5.921      75.7       0.081                  0.048   
...            ...       ...         ...                    ...   
52411        7.010      72.4       0.080                  0.040   
52412        6.947      72.6       0.082                  0.051   
52413        6.900      72.8       0.086                  0.084   
52414        6.758      73.0       0.080                  0.066   
52415        6.580      74.1       0.081                  0.062   

       diffuse flows  hour  day_of_week  month  
0              0.119     0            6      1  
1              0.085     0            6      1  
2              0.100     0            6      1  
3              0.096     0            6      1  
4              0.085     0            6      1  
...              ...   ...          ...    ...  
52411          0.096    23            5     12  
52412          0.093    23            5     12  
52413          0.074    23            5     12  
52414          0.089    23            5     12  
52415          0.111    23            5     12  

[52416 rows x 8 columns]

In [82]:
Y = data[['Zone 1 Power Consumption']]

In [83]:
Y

Zone 1 Power Consumption
0                   34055.69620
1                   29814.68354
2                   29128.10127
3                   28228.86076
4                   27335.69620
...                         ...
52411               31160.45627
52412               30430.41825
52413               29590.87452
52414               28958.17490
52415               28349.80989

[52416 rows x 1 columns]

In [50]:
lr1 = linear_model.LinearRegression()

In [51]:
lr1

LinearRegression()

In [52]:
lr1.fit(X,Y)

LinearRegression()

In [53]:
lr1.coef_

array([[ 4.45392914e+02,  5.62628960e+00,  5.48467072e+01,
        -4.91395678e-01, -4.77474664e+00,  6.92742022e+02,
        -2.35957154e+02, -2.53262788e+02]])

In [54]:
lr1.intercept_

array([18313.94540047])

In [55]:
lr1.predict([[7.567,75.9,0.090,0.079,0.152,15,5,3]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[30566.99678399]])

In [79]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [57]:
model = LinearRegression()
model.fit(X_train, Y_train)


LinearRegression()

In [58]:
# Step 5: Make predictions
Y_pred = model.predict(X_test)


In [96]:
mse = mean_squared_error(Y_test, Y_pred)
mae = mean_absolute_error(Y_test, Y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, Y_pred)

print("MAPE: ", mean_absolute_percentage_error(Y_test, Y_pred))
print("R² Score:", r2)
print("Mean Squared Error (MSE):", mse)
print("Mean Absolute Error (MAE):", mae)
print("Real Mean Squared Error (RMSE): ", rmse)

MAPE:  0.10686074607615209
R² Score: 0.6483094973134027
Mean Squared Error (MSE): 17758396.13786405
Mean Absolute Error (MAE): 3345.1405371040523
Real Mean Squared Error (RMSE):  4214.071207023447


In [61]:
from xgboost import XGBRegressor

xgb = XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=5, random_state=42)

xgb.fit(X_train, Y_train)

Y_pred_xgb = xgb.predict(X_test)


In [91]:
mae = mean_absolute_error(Y_test, Y_pred_xgb)
mse = mean_squared_error(Y_test, Y_pred_xgb)
rmse = np.sqrt(mse)

print("XGBoost MAE:", mae)
print("XGBoost MSE:", mse)
print("XGBoost RMSE:", rmse)
print("XGBoost MAPE: ", mean_absolute_percentage_error(Y_test, Y_pred_xgb))
print("R2:", r2_score(Y_test, Y_pred_xgb))


XGBoost MAE: 1208.6247343976536
XGBoost MSE: 2685729.112291783
XGBoost RMSE: 1638.819426383451
XGBoost MAPE:  0.03842451868263183
R2: 0.9468113328338257


In [64]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [65]:
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train_scaled, Y_train)

KNeighborsRegressor()

In [66]:
Y_pred_knn = knn.predict(X_test_scaled)

In [92]:
mse = mean_squared_error(Y_test, Y_pred_knn)
rmse = np.sqrt(mse)

print("MSE:", mse)
print("RMSE:", rmse)
print("MAE:", mean_absolute_error(Y_test, Y_pred_knn))
print("R2:", r2_score(Y_test, Y_pred_knn))
print("MAPE: ", mean_absolute_percentage_error(Y_test, Y_pred_knn))


MSE: 1504169.513363691
RMSE: 1226.4458868469048
MAE: 787.9451855784051
R2: 0.970211153745309
MAPE:  0.024982739679053012


In [84]:
from sklearn.ensemble import RandomForestRegressor

In [85]:
rf = RandomForestRegressor(n_estimators = 100, random_state = 42)

In [86]:
rf.fit(X_train, Y_train)

RandomForestRegressor(random_state=42)

In [87]:
Y_pred_rf = rf.predict(X_test)

In [93]:
mse = mean_squared_error(Y_test, Y_pred_rf)
rmse = np.sqrt(mse)

print("MSE:", mse)
print("RMSE:", rmse)
print("MAE:", mean_absolute_error(Y_test, Y_pred_rf))
print("R2:", r2_score(Y_test, Y_pred_rf))
print("MAPE: ", mean_absolute_percentage_error(Y_test, Y_pred_rf))

MSE: 1123102.7629214453
RMSE: 1059.765428253557
MAE: 709.1218271317819
R2: 0.9777578688866856
MAPE:  0.022440261316331405
